### ISSUE TITLE
How to compile for windows?

### ISSUE THREAD

**Issue by FreddyE1982** [vaderf/libretro-pcsx2-launcher#1]
How do I compile this for use with the Windows Version of RetroArch?

**Comment by vaderf** [comment]
Hi @FreddyE1982,

Sorry for the very very late response (just saw the issue message). I probably overlooked the notification if I received any.

I think this issue is not relevant anymore as a [PCSX2 core](https://docs.libretro.com/library/pcsx2/) is now available from retroarch.

If still interested, not being a Windows user, I don't really know what modifications are needed. I would say that `install.sh` needs to be rewritten and `Makefile` probably adapted but even so, I doubt this will work out of the box as the behavior of Windows terminal is different from a Unix terminal.

I am afraid I won't be able to provide any help on this.
